parameters:
#    hexmedia_administrator.example.class: Hexmedia\AdministratorBundle\Example

services:
    hexmedia_administrator.menu_builder:
        class: Hexmedia\AdministratorBundle\Menu\Builder
        arguments: ["@event_dispatcher", "@knp_menu.factory", "@security.context", "@translator"]

    hexmedia_administrator.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: hexmedia_administrator.menu_builder
        factory_method: createMainMenu
        arguments: []
        tags:
            - { name: knp_menu.menu, alias: main }

    assetic.filter.assetsurl:
        class: Hexmedia\AdministratorBundle\Filter\AssetsUrl
        arguments:
            - "@service_container"
        tags:
            -	{ name: assetic.filter, alias: assetsurl }

    hexmedia.admin.admin_toolbar:
        class: Hexmedia\AdministratorBundle\EventListener\ToolbarListener
        arguments:
            - "@security.context"
            - "@twig"
        tags:
            - { name: kernel.event_subscriber }


    hexmedia.admin.fields.yesno:
        class: Hexmedia\AdministratorBundle\Form\Fields\YesNoType
        tags:
            - { name: form.type, alias: yesno }

    hexmedia.admin.fields.publication:
        class: Hexmedia\AdministratorBundle\Form\Fields\PublicationType
        tags:
            - { name: form.type, alias: publication }

    hexmedia.admin.fields.datepicker:
        class: Hexmedia\AdministratorBundle\Form\Fields\DatepickerType
        tags:
            - { name: form.type, alias: datepicker }