parameters:
#    hexmedia_administrator.example.class: Hexmedia\AdministratorBundle\Example

services:
    hexmedia_administrator.menu_builder:
        class: Hexmedia\AdministratorBundle\Menu\Builder
        arguments: ["@event_dispatcher", "@knp_menu.factory", "@security.context", "@translator"]

    hexmedia_administrator.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: hexmedia_administrator.menu_builder
        factory_method: createMainMenu
        arguments: []
        tags:
            - { name: knp_menu.menu, alias: main }

    hexmedia_administrator.content_extension:
        class: Hexmedia\AdministratorBundle\Twig\Extension\ContentExtension
        arguments: [ "@doctrine.orm.entity_manager", "@service_container" ]
        tags:
            - { name: twig.extension }

    assetic.filter.assetsurl:
        class: Hexmedia\AdministratorBundle\Filter\AssetsUrl
        arguments:
            - "@service_container"
        tags:
            -	{ name: assetic.filter, alias: assetsurl }

    hexmedia_administrator.admin_toolbar:
        class: Hexmedia\AdministratorBundle\EventListener\ToolbarListener
        arguments:
            - "@security.context"
            - "@twig"
        tags:
            - { name: kernel.event_subscriber }


    hexmedia_administrator.fields.yesno:
        class: Hexmedia\AdministratorBundle\Form\Fields\YesNoType
        tags:
            - { name: form.type, alias: yesno }

    hexmedia_administrator.fields.publication:
        class: Hexmedia\AdministratorBundle\Form\Fields\PublicationType
        tags:
            - { name: form.type, alias: publication }

    hexmedia_administrator.fields.datepicker:
        class: Hexmedia\AdministratorBundle\Form\Fields\DatepickerType
        tags:
            - { name: form.type, alias: datepicker }

    hexmedia_administrator.fields.raptor:
        class: Hexmedia\AdministratorBundle\Form\Fields\RaptorType
        tags:
            - { name: form.type, alias: raptor }

    hexmedia_administrator.fields.raptor:
        class: Hexmedia\AdministratorBundle\Form\Fields\ColorType
        tags:
            - { name: form.type, alias: color }

    hexmedia_administrator.content:
        class: Hexmedia\AdministratorBundle\EditMode\UpdaterChain

    hexmedia.admin.twig.list_script:
        class: Hexmedia\AdministratorBundle\Twig\Extension\ListScriptExtension
        arguments: [ "@router" ]
        tags:
            - { name: twig.extension }