<?php

namespace Hexmedia\AdministratorBundle\Repository\Doctrine;

use Doctrine\ORM\EntityRepository;
use Hexmedia\AdministratorBundle\Repository\ConfigurationRepositoryInterface;
use Hexmedia\AdministratorBundle\Repository\Doctrine\ListTrait;

/**
 * ConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends EntityRepository implements ConfigurationRepositoryInterface {
    use ListTrait;

}
